const DEFAULT_ERROR = 500;

const INVALID_ERROR_CODE = 400;

const NOT_FOUND_ERROR = 404;

const FORBIDDEN_ERROR = 403;

const UNAUTHORIZED_ERROR = 401;

const CONFLICT_ERROR = 409;

module.exports = {
  DEFAULT_ERROR,
  INVALID_ERROR_CODE,
  NOT_FOUND_ERROR,
  FORBIDDEN_ERROR,
  CONFLICT_ERROR,
  UNAUTHORIZED_ERROR,
};
