const DEFAULT_ERROR = 500;

const INVALID_ERROR_CODE = 400;

const NOT_FOUND_ERROR = 404;

const FORBIDDEN_ERROR = 403;

module.exports = {
  DEFAULT_ERROR,
  INVALID_ERROR_CODE,
  NOT_FOUND_ERROR,
  FORBIDDEN_ERROR,
};
